# Generated by Django 4.2.16 on 2026-08-12 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('working_hours', models.TextField(help_text='Формат: Пн-Пт: 8:00-20:00', verbose_name='Время работы')),
                ('map_url', models.URLField(blank=True, verbose_name='Ссылка на карту')),
                ('map_embed', models.TextField(blank=True, verbose_name='Код внедрения карты')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
