# Generated by Django 4.2.16 on 2026-08-12 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conclusion', models.TextField(verbose_name='Заключение')),
                ('recommendations', models.TextField(blank=True, verbose_name='Рекомендации')),
                ('doctor', models.CharField(max_length=100, verbose_name='Врач')),
                ('result_date', models.DateField(auto_now_add=True, verbose_name='Дата результата')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='results/%Y/%m/', verbose_name='Файл результата (PDF)')),
                ('is_normal', models.BooleanField(default=True, help_text='Поставьте галочку, если показатели в норме', verbose_name='В норме')),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='users.appointment', verbose_name='Запись на приём')),
            ],
            options={
                'verbose_name': 'Результат диагностики',
                'verbose_name_plural': 'Результаты диагностики',
                'ordering': ['-result_date'],
            },
        ),
    ]
