# Generated by Django 4.2.16 on 2026-09-12 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_diagnosticresult"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="appointment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ("pending", "confirmed"))),
                fields=("service", "date", "time"),
                name="unique_active_booking_per_slot",
            ),
        ),
    ]
