# Generated by Django 4.2.16 on 2026-09-12 18:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_appointment_unique_active_booking_per_slot"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="telegram_chat_id",
            field=models.BigIntegerField(blank=True, null=True, verbose_name="Telegram chat ID"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="telegram_link_code",
            field=models.CharField(blank=True, max_length=32, unique=True, verbose_name="Код привязки Telegram"),
        ),
    ]
