# Generated by Django 4.2.16 on 2026-09-12

import uuid

from django.db import migrations, models


def fill_link_codes(apps, schema_editor):
    """Заполняет пустые коды привязки уникальными значениями перед включением unique."""
    UserProfile = apps.get_model("users", "UserProfile")
    profiles = UserProfile.objects.filter(models.Q(telegram_link_code="") | models.Q(telegram_link_code__isnull=True))
    for profile in profiles:
        profile.telegram_link_code = uuid.uuid4().hex
        profile.save(update_fields=("telegram_link_code",))


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_userprofile_telegram_chat_id_and_more"),
    ]

    operations = [
        migrations.RunPython(fill_link_codes, migrations.RunPython.noop),
    ]
