# Generated by Django 4.2.16 on 2026-09-12 19:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_fill_telegram_link_codes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="telegram_link_code",
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name="Код привязки Telegram"),
        ),
    ]
